export const ProfileTypeList = [
    "Just Friends",
    "Activity Partner",
    "Virtual Relationship",
    "Open Relationship",
    "Short Relationship",
    "Long Relationship",
    "Business Partner",
    "Career Opportunities"
];
export const languageList = [
    "Arabic", "Bengali", "Cantonese", "Chinese", "Dutch", "English", "French", "German", "Guajarati", "Hebrew", "Hindi", "Italian"
    , "Japanese", "Kannada", "Konkani", "Malayalam", "Mandarin", "Marathi", "Norwegian", "Oriya", "Persian", "Portuguese", "Punjabi", "Russian", "Sanskrit"
    , "Sindhi", "Sinhalese", "Spanish", "Swahili", "Swedish", "Tagalong", "Tamil", "Telugu", "Thai", "Urdu", "Vietnamese"
];
export const GenderList =
    [
        "No Prefrences", "Male", "Female"
    ];
export const MaritalStatusList =
    [
        "No Prefrences",
        "Never Married",
        "Single",
        "Annulled",
        "Separated",
        "Widowed",
        "Divorced",
        "Awaiting Divorce",
        "Live-in Partner",
        "Open Relatioship",
        "Committed Relationship",
        "Engaged",
        "Married"
    ];
export const ChildrenList =
    [
        "No Prefrences",
        "Zero",
        "Yes, and they always live at home",
        "Yes, and they sometimes they live at home",
        "Yes, and they never live at home",
        "Yes, and I am not in touch with them",
        "No, but I  definitely want to have some day",
        "No, but I probably want to have some day",
        "No, and I probably don’t want to have any",
        "No, and I definitely don’t want to have any"];
export const SexualityList =
    [
        "No Prefrences",
        "Straight",
        "Gay",
        "Lesbian",
        "Bisexual"
    ];
export const ReligionList = [
    "No Prefrences",
    "Agnostic",
    "Atheist",
    "Buddhist / Taoist",
    "Christian – Catholic",
    "Christian – LDS",
    "Christian – Protestant",
    "Christian – Other",
    "Hindu",
    "Jewish",
    "Scientology",
    "Sikh",
    "Muslim / Islam",
    "No Religion",
    "Other"
];
export const EthnicityList =
    [
        "No Prefrences",
        "Asian",
        "Black/African Descent",
        "East Indian/Indian Subcontinent",
        "Latino/Hispanic",
        "Middle Eastern",
        "Native American",
        "Pacific Islander",
        "White/Caucasian",
        "Other"
    ];
export const PoliticalList =
    [
        "No Prefrences",
        "AsiVery Liberalan",
        "Liberal",
        "Middle of the Road",
        "Centrist",
        "Conservative",
        "Ultra Conservative",
        "Non-conformist"
    ];
export const DisabilitylList =
    [
        "No Prefrences",
        "Physical Disability",
        "Medical Disability",
        "Psychiatric Disability",
        "Learning Disability",
        "Developmental Disability",
        "Attention Disability",
        "Mobility Impairment",
        "Speech Impairment",
        "Hearing Impairment",
        "Vision Impairment",
        "Other Disability"
    ];
export const HeightList =
    [
        "No Prefrences",
        "Short",
        "Average",
        "Medium",
        "Tall",
    ];
export const PhysiqueList =
    [
        "No Prefrences",
        "Slender",
        "Slim",
        "Toned",
        "Athletic",
        "Average",
        "Curvy",
        "Plump",
        "Few Extra Pounds",
        "Full-figured",
        "Big and Beautiful",
        "Stocky",
        "Heavyset"
    ];
export const EyeList =
    [
        "No Prefrences",
        "Blue",
        "Brown",
        "Green",
        "Grey",
        "Black",
        "Hazel"
    ];
export const HairList =
    [
        "No Prefrences",
        "Black",
        "Blonde",
        "Auburn/Red",
        "Light Brown",
        "Dark Brown",
        "Platinum",
        "Grey",
        "Salt n Pepper",
        "Silver",
        "Dark Blonde",
        "Short",
        "Long",
        "Bald"
    ];
export const DietList =
    [
        "No Prefrences",
        "Vegetarian",
        "Vegan",
        "Eggatarian",
        "NonVegetarian"
    ];
export const DrinkList =
    [
        "No Prefrences",
        "Never",
        "Socially",
        "Occasionally",
        "Moderatly",
        "Regularly",
        "Daily"
    ];
export const SmokeList =
    [
        "No Prefrences",
        "Never",
        "Socially",
        "Occasionally",
        "Moderatly",
        "Regularly",
    ];
export const ExerciseList =
    [
        "No Prefrences",
        "Never",
        "Occasionally",
        "Sporadically",
        "Infrequently",
        "Periodically",
        "Regularly",
        "Daily"
    ];
export const HighesteduList =
    [
        "No Prefrences",
        "Less than High School",
        "High School",
        "Trade School",
        "Associates Degree",
        "Diploma",
        "Some college",
        "Bachelors/Undergrad Degree",
        "Masters/Grad Degree",
        "Honors Degree",
        "Joint Degree",
        "Double Degree",
        "Doctorate/PhD"
    ];
export const SectorList =
    [
        "No Prefrences",
        "Private Sector",
        "Public Sector",
        "Government Sector",
        "Defense Sector",
        "Civil Services",
        "Business Establishment"
    ];
export const ProfStatusList =
    [
        "No Prefrences",
        "Working Full-Time",
        "Working Part-Time",
        "Full-Time Student",
        "Part-Time Student",
        "Between Jobs",
        "Retired",
        "Home Maker",
        "Not Working"
    ];
export const ProfessionList =
    [
        "No Prefrences",
        "Accountant / Bookkeeper",
        "Actor / Artist",
        "Administrator / Manager ",
        "Agent / Broker",
        "Assistant / Secretary",
        "Advertising / Marketing",
        "Airline Staff",
        "Architect / Interiors",
        "Artisan / Craftsman",
        "Banker / Finance",
        "Beautician / Cosmetologist",
        "Chef / Sommelier ",
        "Chief Executive / CXO ",
        "Constructor / Contractor ",
        "Consultant / Advisor ",
        "Customer Service ",
        "Defense / Forces ",
        "Dentist / Dental ",
        "Dietician / Nutritionist ",
        "Doctor / Physician  ",
        "Ecologist / Environmentalist ",
        "Engineer / Technologist ",
        "Entrepreneur / Businessperson ",
        "Entertainer / Performer ",
        "Events / Exhibitions",
        "Farmer / Agriculturist",
        "Fashion / Apparel",
        "Fitness / Wellness ",
        "Government Servant",
        "Graphics / Animator",
        "Hospitality / Hotels",
        "Human / Resources",
        "IT / Telecom",
        "Insurance / Retirement",
        "Investor / VC",
        "Law / Enforcement",
        "Legal / Lawyer",
        "Media / Journalist",
        "Medical / Health-Care",
        "Merchant / Navy",
        "Nurse / Caregiver",
        "Optician / Optometrist",
        "Pharmacist / Chemist",
        "Phycologist / Psychiatrist",
        "Pilot / Aviation",
        "Politician / Legislator",
        "Production / Manufacturing",
        "Real / Estate",
        "Religious / Spiritual",
        "Researcher / Scientist",
        "Retailer / Salesperson",
        "Social / Worker",
        "Sportsperson / Athlete",
        "Student / Scholar",
        "Teacher / Professor",
        "Technician / Mechanic",
        "Travel / Tourism",
        "Upper / Management",
        "Volunteer/  Worker",
        "Writer / Editor",
        "Other"
    ];
export const IndustryList =
    [
        "No Prefrences",
        "Accounting",
        "Administrative Services",
        "Advertising / Marketing",
        "Agriculture / Farming",
        "Airline / Aviation",
        "Alternate Medicine",
        "Architecture/Planning",
        "Armed Forces"
    ];
export const IncomeList =
    [
        "No Prefrences",
        "Zero",
        "Very Low",
        "Low",
        "Medium",
        "High",
        "Very High",
        "Exorbitant"
    ];
export const ActivityLevelList =
    [
        "No Prefrences",
        "Always on the Run",
        "Out n About",
        "Extremely Active",
        "Very Active",
        "Not very Active"
    ];
export const LovaRomanceImages = [
    "assets/images/love-romance/attraction-crushes.jpg",
    "assets/images/love-romance/chemistry-connection.jpg",
    "assets/images/love-romance/dating-courtship.jpg",
    "assets/images/love-romance/flirting-seducing.jpg",
    "assets/images/love-romance/friends-acquaintances.jpg",
    "assets/images/love-romance/gays-lesbians.jpg",
    "assets/images/love-romance/harmony-compatibility.jpg",
    "assets/images/love-romance/heartbreaks-breakups.jpg",
    "assets/images/love-romance/hookups-affairs.jpg",
    "assets/images/love-romance/infidelity-cheating.jpg",
    "assets/images/love-romance/ispace1-stripe.jpg",
    "assets/images/love-romance/ispace1-world.jpg",
    "assets/images/love-romance/love-romance.jpg",
    "assets/images/love-romance/marriage-matrimony.jpg",
    "assets/images/love-romance/relationship-commitment.jpg",
    "assets/images/love-romance/sex-intimacy.jpg",
    "assets/images/love-romance/singles-unattached.jpg",
    "assets/images/love-romance/spouses-couples.jpg"
]
export const AbbreviationsAcronyms = [
    "assets/images/abbreviations-acronyms/attraction-crushes.jpg",
    "assets/images/abbreviations-acronyms/chemistry-connection.jpg",
    "assets/images/abbreviations-acronyms/dating-courtship.jpg",
    "assets/images/abbreviations-acronyms/flirting-seducing.jpg",
    "assets/images/abbreviations-acronyms/friends-acquaintances.jpg",
    "assets/images/abbreviations-acronyms/gays-lesbians.jpg",
    "assets/images/abbreviations-acronyms/harmony-compatibility.jpg",
    "assets/images/abbreviations-acronyms/heartbreaks-breakups.jpg",
    "assets/images/abbreviations-acronyms/hookups-affairs.jpg",
    "assets/images/abbreviations-acronyms/infidelity-cheating.jpg",
    "assets/images/abbreviations-acronyms/ispace1-stripe.jpg",
    "assets/images/abbreviations-acronyms/ispace1-world.jpg",
    "assets/images/abbreviations-acronyms/love-romance.jpg",
    "assets/images/abbreviations-acronyms/marriage-matrimony.jpg",
    "assets/images/abbreviations-acronyms/relationship-commitment.jpg",
    "assets/images/abbreviations-acronyms/sex-intimacy.jpg",
    "assets/images/abbreviations-acronyms/singles-unattached.jpg",
    "assets/images/abbreviations-acronyms/spouses-couples.jpg"
]
export const ActivityPartner = [
    "assets/images/activity-partner/attraction-crushes.jpg",
    "assets/images/activity-partner/chemistry-connection.jpg",
    "assets/images/activity-partner/dating-courtship.jpg",
    "assets/images/activity-partner/flirting-seducing.jpg",
    "assets/images/activity-partner/friends-acquaintances.jpg",
    "assets/images/activity-partner/gays-lesbians.jpg",
    "assets/images/activity-partner/harmony-compatibility.jpg",
    "assets/images/activity-partner/heartbreaks-breakups.jpg",
    "assets/images/activity-partner/hookups-affairs.jpg",
    "assets/images/activity-partner/infidelity-cheating.jpg",
    "assets/images/activity-partner/ispace1-stripe.jpg",
    "assets/images/activity-partner/ispace1-world.jpg",
    "assets/images/activity-partner/love-romance.jpg",
    "assets/images/activity-partner/marriage-matrimony.jpg",
    "assets/images/activity-partner/relationship-commitment.jpg",
    "assets/images/activity-partner/sex-intimacy.jpg",
    "assets/images/activity-partner/singles-unattached.jpg",
    "assets/images/activity-partner/spouses-couples.jpg"
]
export const AstrologyHoroscope = [
    "assets/images/astrology-horoscope/attraction-crushes.jpg",
    "assets/images/astrology-horoscope/chemistry-connection.jpg",
    "assets/images/astrology-horoscope/dating-courtship.jpg",
    "assets/images/astrology-horoscope/flirting-seducing.jpg",
    "assets/images/astrology-horoscope/friends-acquaintances.jpg",
    "assets/images/astrology-horoscope/gays-lesbians.jpg",
    "assets/images/astrology-horoscope/harmony-compatibility.jpg",
    "assets/images/astrology-horoscope/heartbreaks-breakups.jpg",
    "assets/images/astrology-horoscope/hookups-affairs.jpg",
    "assets/images/astrology-horoscope/infidelity-cheating.jpg",
    "assets/images/astrology-horoscope/ispace1-stripe.jpg",
    "assets/images/astrology-horoscope/ispace1-world.jpg",
    "assets/images/astrology-horoscope/love-romance.jpg",
    "assets/images/astrology-horoscope/marriage-matrimony.jpg",
    "assets/images/astrology-horoscope/relationship-commitment.jpg",
    "assets/images/astrology-horoscope/sex-intimacy.jpg",
    "assets/images/astrology-horoscope/singles-unattached.jpg",
    "assets/images/astrology-horoscope/spouses-couples.jpg"
]
export const AttractionCrushes = [
    "assets/images/attraction-crushes/attraction-crushes.jpg",
    "assets/images/attraction-crushes/chemistry-connection.jpg",
    "assets/images/attraction-crushes/dating-courtship.jpg",
    "assets/images/attraction-crushes/flirting-seducing.jpg",
    "assets/images/attraction-crushes/friends-acquaintances.jpg",
    "assets/images/attraction-crushes/gays-lesbians.jpg",
    "assets/images/attraction-crushes/harmony-compatibility.jpg",
    "assets/images/attraction-crushes/heartbreaks-breakups.jpg",
    "assets/images/attraction-crushes/hookups-affairs.jpg",
    "assets/images/attraction-crushes/infidelity-cheating.jpg",
    "assets/images/attraction-crushes/ispace1-stripe.jpg",
    "assets/images/attraction-crushes/ispace1-world.jpg",
    "assets/images/attraction-crushes/love-romance.jpg",
    "assets/images/attraction-crushes/marriage-matrimony.jpg",
    "assets/images/attraction-crushes/relationship-commitment.jpg",
    "assets/images/attraction-crushes/sex-intimacy.jpg",
    "assets/images/attraction-crushes/singles-unattached.jpg",
    "assets/images/attraction-crushes/spouses-couples.jpg"
]
export const BusinessPartner = [
    "assets/images/business-partner/attraction-crushes.jpg",
    "assets/images/business-partner/chemistry-connection.jpg",
    "assets/images/business-partner/dating-courtship.jpg",
    "assets/images/business-partner/flirting-seducing.jpg",
    "assets/images/business-partner/friends-acquaintances.jpg",
    "assets/images/business-partner/gays-lesbians.jpg",
    "assets/images/business-partner/harmony-compatibility.jpg",
    "assets/images/business-partner/heartbreaks-breakups.jpg",
    "assets/images/business-partner/hookups-affairs.jpg",
    "assets/images/business-partner/infidelity-cheating.jpg",
    "assets/images/business-partner/ispace1-stripe.jpg",
    "assets/images/business-partner/ispace1-world.jpg",
    "assets/images/business-partner/love-romance.jpg",
    "assets/images/business-partner/marriage-matrimony.jpg",
    "assets/images/business-partner/relationship-commitment.jpg",
    "assets/images/business-partner/sex-intimacy.jpg",
    "assets/images/business-partner/singles-unattached.jpg",
    "assets/images/business-partner/spouses-couples.jpg"
]
export const CareerOpportunities = [
    "assets/images/career-opportunities/attraction-crushes.jpg",
    "assets/images/career-opportunities/chemistry-connection.jpg",
    "assets/images/career-opportunities/dating-courtship.jpg",
    "assets/images/career-opportunities/flirting-seducing.jpg",
    "assets/images/career-opportunities/friends-acquaintances.jpg",
    "assets/images/career-opportunities/gays-lesbians.jpg",
    "assets/images/career-opportunities/harmony-compatibility.jpg",
    "assets/images/career-opportunities/heartbreaks-breakups.jpg",
    "assets/images/career-opportunities/hookups-affairs.jpg",
    "assets/images/career-opportunities/infidelity-cheating.jpg",
    "assets/images/career-opportunities/ispace1-stripe.jpg",
    "assets/images/career-opportunities/ispace1-world.jpg",
    "assets/images/career-opportunities/love-romance.jpg",
    "assets/images/career-opportunities/marriage-matrimony.jpg",
    "assets/images/career-opportunities/relationship-commitment.jpg",
    "assets/images/career-opportunities/sex-intimacy.jpg",
    "assets/images/career-opportunities/singles-unattached.jpg",
    "assets/images/career-opportunities/spouses-couples.jpg"
]
export const ChemistryConnection = [
    "assets/images/chemistry-connection/attraction-crushes.jpg",
    "assets/images/chemistry-connection/chemistry-connection.jpg",
    "assets/images/chemistry-connection/dating-courtship.jpg",
    "assets/images/chemistry-connection/flirting-seducing.jpg",
    "assets/images/chemistry-connection/friends-acquaintances.jpg",
    "assets/images/chemistry-connection/gays-lesbians.jpg",
    "assets/images/chemistry-connection/harmony-compatibility.jpg",
    "assets/images/chemistry-connection/heartbreaks-breakups.jpg",
    "assets/images/chemistry-connection/hookups-affairs.jpg",
    "assets/images/chemistry-connection/infidelity-cheating.jpg",
    "assets/images/chemistry-connection/ispace1-stripe.jpg",
    "assets/images/chemistry-connection/ispace1-world.jpg",
    "assets/images/chemistry-connection/love-romance.jpg",
    "assets/images/chemistry-connection/marriage-matrimony.jpg",
    "assets/images/chemistry-connection/relationship-commitment.jpg",
    "assets/images/chemistry-connection/sex-intimacy.jpg",
    "assets/images/chemistry-connection/singles-unattached.jpg",
    "assets/images/chemistry-connection/spouses-couples.jpg"
]
export const DatingCourtship = [
    "assets/images/Dating-Courtship/attraction-crushes.jpg",
    "assets/images/Dating-Courtship/chemistry-connection.jpg",
    "assets/images/Dating-Courtship/dating-courtship.jpg",
    "assets/images/Dating-Courtship/flirting-seducing.jpg",
    "assets/images/Dating-Courtship/friends-acquaintances.jpg",
    "assets/images/Dating-Courtship/gays-lesbians.jpg",
    "assets/images/Dating-Courtship/harmony-compatibility.jpg",
    "assets/images/Dating-Courtship/heartbreaks-breakups.jpg",
    "assets/images/Dating-Courtship/hookups-affairs.jpg",
    "assets/images/Dating-Courtship/infidelity-cheating.jpg",
    "assets/images/Dating-Courtship/ispace1-stripe.jpg",
    "assets/images/Dating-Courtship/ispace1-world.jpg",
    "assets/images/Dating-Courtship/love-romance.jpg",
    "assets/images/Dating-Courtship/marriage-matrimony.jpg",
    "assets/images/Dating-Courtship/relationship-commitment.jpg",
    "assets/images/Dating-Courtship/sex-intimacy.jpg",
    "assets/images/Dating-Courtship/singles-unattached.jpg",
    "assets/images/Dating-Courtship/spouses-couples.jpg"
]
export const Extra = [
    "assets/images/Extra-Extra/attraction-crushes.jpg",
    "assets/images/Extra-Extra/chemistry-connection.jpg",
    "assets/images/Extra-Extra/dating-courtship.jpg",
    "assets/images/Extra-Extra/flirting-seducing.jpg",
    "assets/images/Extra-Extra/friends-acquaintances.jpg",
    "assets/images/Extra-Extra/gays-lesbians.jpg",
    "assets/images/Extra-Extra/harmony-compatibility.jpg",
    "assets/images/Extra-Extra/heartbreaks-breakups.jpg",
    "assets/images/Extra-Extra/hookups-affairs.jpg",
    "assets/images/Extra-Extra/infidelity-cheating.jpg",
    "assets/images/Extra-Extra/ispace1-stripe.jpg",
    "assets/images/Extra-Extra/ispace1-world.jpg",
    "assets/images/Extra-Extra/love-romance.jpg",
    "assets/images/Extra-Extra/marriage-matrimony.jpg",
    "assets/images/Extra-Extra/relationship-commitment.jpg",
    "assets/images/Extra-Extra/sex-intimacy.jpg",
    "assets/images/Extra-Extra/singles-unattached.jpg",
    "assets/images/Extra-Extra/spouses-couples.jpg"
]
export const Extras = [
    "assets/images/Extras-Extras/attraction-crushes.jpg",
    "assets/images/Extras-Extras/chemistry-connection.jpg",
    "assets/images/Extras-Extras/dating-courtship.jpg",
    "assets/images/Extras-Extras/flirting-seducing.jpg",
    "assets/images/Extras-Extras/friends-acquaintances.jpg",
    "assets/images/Extras-Extras/gays-lesbians.jpg",
    "assets/images/Extras-Extras/harmony-compatibility.jpg",
    "assets/images/Extras-Extras/heartbreaks-breakups.jpg",
    "assets/images/Extras-Extras/hookups-affairs.jpg",
    "assets/images/Extras-Extras/infidelity-cheating.jpg",
    "assets/images/Extras-Extras/ispace1-stripe.jpg",
    "assets/images/Extras-Extras/ispace1-world.jpg",
    "assets/images/Extras-Extras/love-romance.jpg",
    "assets/images/Extras-Extras/marriage-matrimony.jpg",
    "assets/images/Extras-Extras/relationship-commitment.jpg",
    "assets/images/Extras-Extras/sex-intimacy.jpg",
    "assets/images/Extras-Extras/singles-unattached.jpg",
    "assets/images/Extras-Extras/spouses-couples.jpg"
]
export const FlirtingSeducing = [
    "assets/images/Flirting-Seducing/attraction-crushes.jpg",
    "assets/images/Flirting-Seducing/chemistry-connection.jpg",
    "assets/images/Flirting-Seducing/dating-courtship.jpg",
    "assets/images/Flirting-Seducing/flirting-seducing.jpg",
    "assets/images/Flirting-Seducing/friends-acquaintances.jpg",
    "assets/images/Flirting-Seducing/gays-lesbians.jpg",
    "assets/images/Flirting-Seducing/harmony-compatibility.jpg",
    "assets/images/Flirting-Seducing/heartbreaks-breakups.jpg",
    "assets/images/Flirting-Seducing/hookups-affairs.jpg",
    "assets/images/Flirting-Seducing/infidelity-cheating.jpg",
    "assets/images/Flirting-Seducing/ispace1-stripe.jpg",
    "assets/images/Flirting-Seducing/ispace1-world.jpg",
    "assets/images/Flirting-Seducing/love-romance.jpg",
    "assets/images/Flirting-Seducing/marriage-matrimony.jpg",
    "assets/images/Flirting-Seducing/relationship-commitment.jpg",
    "assets/images/Flirting-Seducing/sex-intimacy.jpg",
    "assets/images/Flirting-Seducing/singles-unattached.jpg",
    "assets/images/Flirting-Seducing/spouses-couples.jpg"
]
export const FriendsAcquaintances = [
    "assets/images/Friends-Acquaintances/attraction-crushes.jpg",
    "assets/images/Friends-Acquaintances/chemistry-connection.jpg",
    "assets/images/Friends-Acquaintances/dating-courtship.jpg",
    "assets/images/Friends-Acquaintances/flirting-seducing.jpg",
    "assets/images/Friends-Acquaintances/friends-acquaintances.jpg",
    "assets/images/Friends-Acquaintances/gays-lesbians.jpg",
    "assets/images/Friends-Acquaintances/harmony-compatibility.jpg",
    "assets/images/Friends-Acquaintances/heartbreaks-breakups.jpg",
    "assets/images/Friends-Acquaintances/hookups-affairs.jpg",
    "assets/images/Friends-Acquaintances/infidelity-cheating.jpg",
    "assets/images/Friends-Acquaintances/ispace1-stripe.jpg",
    "assets/images/Friends-Acquaintances/ispace1-world.jpg",
    "assets/images/Friends-Acquaintances/love-romance.jpg",
    "assets/images/Friends-Acquaintances/marriage-matrimony.jpg",
    "assets/images/Friends-Acquaintances/relationship-commitment.jpg",
    "assets/images/Friends-Acquaintances/sex-intimacy.jpg",
    "assets/images/Friends-Acquaintances/singles-unattached.jpg",
    "assets/images/Friends-Acquaintances/spouses-couples.jpg"
]
export const GaysLesbians = [
    "assets/images/Gays-Lesbians/attraction-crushes.jpg",
    "assets/images/Gays-Lesbians/chemistry-connection.jpg",
    "assets/images/Gays-Lesbians/dating-courtship.jpg",
    "assets/images/Gays-Lesbians/flirting-seducing.jpg",
    "assets/images/Gays-Lesbians/friends-acquaintances.jpg",
    "assets/images/Gays-Lesbians/gays-lesbians.jpg",
    "assets/images/Gays-Lesbians/harmony-compatibility.jpg",
    "assets/images/Gays-Lesbians/heartbreaks-breakups.jpg",
    "assets/images/Gays-Lesbians/hookups-affairs.jpg",
    "assets/images/Gays-Lesbians/infidelity-cheating.jpg",
    "assets/images/Gays-Lesbians/ispace1-stripe.jpg",
    "assets/images/Gays-Lesbians/ispace1-world.jpg",
    "assets/images/Gays-Lesbians/love-romance.jpg",
    "assets/images/Gays-Lesbians/marriage-matrimony.jpg",
    "assets/images/Gays-Lesbians/relationship-commitment.jpg",
    "assets/images/Gays-Lesbians/sex-intimacy.jpg",
    "assets/images/Gays-Lesbians/singles-unattached.jpg",
    "assets/images/Gays-Lesbians/spouses-couples.jpg"
]
export const HarmonyCompatibility = [
    "assets/images/Harmony-Compatibility/attraction-crushes.jpg",
    "assets/images/Harmony-Compatibility/chemistry-connection.jpg",
    "assets/images/Harmony-Compatibility/dating-courtship.jpg",
    "assets/images/Harmony-Compatibility/flirting-seducing.jpg",
    "assets/images/Harmony-Compatibility/friends-acquaintances.jpg",
    "assets/images/Harmony-Compatibility/gays-lesbians.jpg",
    "assets/images/Harmony-Compatibility/harmony-compatibility.jpg",
    "assets/images/Harmony-Compatibility/heartbreaks-breakups.jpg",
    "assets/images/Harmony-Compatibility/hookups-affairs.jpg",
    "assets/images/Harmony-Compatibility/infidelity-cheating.jpg",
    "assets/images/Harmony-Compatibility/ispace1-stripe.jpg",
    "assets/images/Harmony-Compatibility/ispace1-world.jpg",
    "assets/images/Harmony-Compatibility/love-romance.jpg",
    "assets/images/Harmony-Compatibility/marriage-matrimony.jpg",
    "assets/images/Harmony-Compatibility/relationship-commitment.jpg",
    "assets/images/Harmony-Compatibility/sex-intimacy.jpg",
    "assets/images/Harmony-Compatibility/singles-unattached.jpg",
    "assets/images/Harmony-Compatibility/spouses-couples.jpg"
]
export const HeartbreaksBreakups = [
    "assets/images/Heartbreaks-Breakups/attraction-crushes.jpg",
    "assets/images/Heartbreaks-Breakups/chemistry-connection.jpg",
    "assets/images/Heartbreaks-Breakups/dating-courtship.jpg",
    "assets/images/Heartbreaks-Breakups/flirting-seducing.jpg",
    "assets/images/Heartbreaks-Breakups/friends-acquaintances.jpg",
    "assets/images/Heartbreaks-Breakups/gays-lesbians.jpg",
    "assets/images/Heartbreaks-Breakups/harmony-compatibility.jpg",
    "assets/images/Heartbreaks-Breakups/heartbreaks-breakups.jpg",
    "assets/images/Heartbreaks-Breakups/hookups-affairs.jpg",
    "assets/images/Heartbreaks-Breakups/infidelity-cheating.jpg",
    "assets/images/Heartbreaks-Breakups/ispace1-stripe.jpg",
    "assets/images/Heartbreaks-Breakups/ispace1-world.jpg",
    "assets/images/Heartbreaks-Breakups/love-romance.jpg",
    "assets/images/Heartbreaks-Breakups/marriage-matrimony.jpg",
    "assets/images/Heartbreaks-Breakups/relationship-commitment.jpg",
    "assets/images/Heartbreaks-Breakups/sex-intimacy.jpg",
    "assets/images/Heartbreaks-Breakups/singles-unattached.jpg",
    "assets/images/Heartbreaks-Breakups/spouses-couples.jpg"
]
export const HookupsAffairs = [
    "assets/images/Hookups-Affairs/attraction-crushes.jpg",
    "assets/images/Hookups-Affairs/chemistry-connection.jpg",
    "assets/images/Hookups-Affairs/dating-courtship.jpg",
    "assets/images/Hookups-Affairs/flirting-seducing.jpg",
    "assets/images/Hookups-Affairs/friends-acquaintances.jpg",
    "assets/images/Hookups-Affairs/gays-lesbians.jpg",
    "assets/images/Hookups-Affairs/harmony-compatibility.jpg",
    "assets/images/Hookups-Affairs/heartbreaks-breakups.jpg",
    "assets/images/Hookups-Affairs/hookups-affairs.jpg",
    "assets/images/Hookups-Affairs/infidelity-cheating.jpg",
    "assets/images/Hookups-Affairs/ispace1-stripe.jpg",
    "assets/images/Hookups-Affairs/ispace1-world.jpg",
    "assets/images/Hookups-Affairs/love-romance.jpg",
    "assets/images/Hookups-Affairs/marriage-matrimony.jpg",
    "assets/images/Hookups-Affairs/relationship-commitment.jpg",
    "assets/images/Hookups-Affairs/sex-intimacy.jpg",
    "assets/images/Hookups-Affairs/singles-unattached.jpg",
    "assets/images/Hookups-Affairs/spouses-couples.jpg"
]
export const idioms = [
    "assets/images/Idioms-Proverbs/attraction-crushes.jpg",
    "assets/images/Idioms-Proverbs/chemistry-connection.jpg",
    "assets/images/Idioms-Proverbs/dating-courtship.jpg",
    "assets/images/Idioms-Proverbs/flirting-seducing.jpg",
    "assets/images/Idioms-Proverbs/friends-acquaintances.jpg",
    "assets/images/Idioms-Proverbs/gays-lesbians.jpg",
    "assets/images/Idioms-Proverbs/harmony-compatibility.jpg",
    "assets/images/Idioms-Proverbs/heartbreaks-breakups.jpg",
    "assets/images/Idioms-Proverbs/hookups-affairs.jpg",
    "assets/images/Idioms-Proverbs/infidelity-cheating.jpg",
    "assets/images/Idioms-Proverbs/ispace1-stripe.jpg",
    "assets/images/Idioms-Proverbs/ispace1-world.jpg",
    "assets/images/Idioms-Proverbs/love-romance.jpg",
    "assets/images/Idioms-Proverbs/marriage-matrimony.jpg",
    "assets/images/Idioms-Proverbs/relationship-commitment.jpg",
    "assets/images/Idioms-Proverbs/sex-intimacy.jpg",
    "assets/images/Idioms-Proverbs/singles-unattached.jpg",
    "assets/images/Idioms-Proverbs/spouses-couples.jpg"
]
export const InfidelityCheating = [
    "assets/images/Infidelity-Cheating/attraction-crushes.jpg",
    "assets/images/Infidelity-Cheating/chemistry-connection.jpg",
    "assets/images/Infidelity-Cheating/dating-courtship.jpg",
    "assets/images/Infidelity-Cheating/flirting-seducing.jpg",
    "assets/images/Infidelity-Cheating/friends-acquaintances.jpg",
    "assets/images/Infidelity-Cheating/gays-lesbians.jpg",
    "assets/images/Infidelity-Cheating/harmony-compatibility.jpg",
    "assets/images/Infidelity-Cheating/heartbreaks-breakups.jpg",
    "assets/images/Infidelity-Cheating/hookups-affairs.jpg",
    "assets/images/Infidelity-Cheating/infidelity-cheating.jpg",
    "assets/images/Infidelity-Cheating/ispace1-stripe.jpg",
    "assets/images/Infidelity-Cheating/ispace1-world.jpg",
    "assets/images/Infidelity-Cheating/love-romance.jpg",
    "assets/images/Infidelity-Cheating/marriage-matrimony.jpg",
    "assets/images/Infidelity-Cheating/relationship-commitment.jpg",
    "assets/images/Infidelity-Cheating/sex-intimacy.jpg",
    "assets/images/Infidelity-Cheating/singles-unattached.jpg",
    "assets/images/Infidelity-Cheating/spouses-couples.jpg"
]
export const JustFriends = [
    "assets/images/Just-Friends/attraction-crushes.jpg",
    "assets/images/Just-Friends/chemistry-connection.jpg",
    "assets/images/Just-Friends/dating-courtship.jpg",
    "assets/images/Just-Friends/flirting-seducing.jpg",
    "assets/images/Just-Friends/friends-acquaintances.jpg",
    "assets/images/Just-Friends/gays-lesbians.jpg",
    "assets/images/Just-Friends/harmony-compatibility.jpg",
    "assets/images/Just-Friends/heartbreaks-breakups.jpg",
    "assets/images/Just-Friends/hookups-affairs.jpg",
    "assets/images/Just-Friends/infidelity-cheating.jpg",
    "assets/images/Just-Friends/ispace1-stripe.jpg",
    "assets/images/Just-Friends/ispace1-world.jpg",
    "assets/images/Just-Friends/love-romance.jpg",
    "assets/images/Just-Friends/marriage-matrimony.jpg",
    "assets/images/Just-Friends/relationship-commitment.jpg",
    "assets/images/Just-Friends/sex-intimacy.jpg",
    "assets/images/Just-Friends/singles-unattached.jpg",
    "assets/images/Just-Friends/spouses-couples.jpg"
]
export const LifeStyle = [
    "assets/images/Life-Style/attraction-crushes.jpg",
    "assets/images/Life-Style/chemistry-connection.jpg",
    "assets/images/Life-Style/dating-courtship.jpg",
    "assets/images/Life-Style/flirting-seducing.jpg",
    "assets/images/Life-Style/friends-acquaintances.jpg",
    "assets/images/Life-Style/gays-lesbians.jpg",
    "assets/images/Life-Style/harmony-compatibility.jpg",
    "assets/images/Life-Style/heartbreaks-breakups.jpg",
    "assets/images/Life-Style/hookups-affairs.jpg",
    "assets/images/Life-Style/infidelity-cheating.jpg",
    "assets/images/Life-Style/ispace1-stripe.jpg",
    "assets/images/Life-Style/ispace1-world.jpg",
    "assets/images/Life-Style/love-romance.jpg",
    "assets/images/Life-Style/marriage-matrimony.jpg",
    "assets/images/Life-Style/relationship-commitment.jpg",
    "assets/images/Life-Style/sex-intimacy.jpg",
    "assets/images/Life-Style/singles-unattached.jpg",
    "assets/images/Life-Style/spouses-couples.jpg"
]
export const LongRelationship = [
    "assets/images/Long-Relationship/attraction-crushes.jpg",
    "assets/images/Long-Relationship/chemistry-connection.jpg",
    "assets/images/Long-Relationship/dating-courtship.jpg",
    "assets/images/Long-Relationship/flirting-seducing.jpg",
    "assets/images/Long-Relationship/friends-acquaintances.jpg",
    "assets/images/Long-Relationship/gays-lesbians.jpg",
    "assets/images/Long-Relationship/harmony-compatibility.jpg",
    "assets/images/Long-Relationship/heartbreaks-breakups.jpg",
    "assets/images/Long-Relationship/hookups-affairs.jpg",
    "assets/images/Long-Relationship/infidelity-cheating.jpg",
    "assets/images/Long-Relationship/ispace1-stripe.jpg",
    "assets/images/Long-Relationship/ispace1-world.jpg",
    "assets/images/Long-Relationship/love-romance.jpg",
    "assets/images/Long-Relationship/marriage-matrimony.jpg",
    "assets/images/Long-Relationship/relationship-commitment.jpg",
    "assets/images/Long-Relationship/sex-intimacy.jpg",
    "assets/images/Long-Relationship/singles-unattached.jpg",
    "assets/images/Long-Relationship/spouses-couples.jpg"
]
export const MarriageWedding = [
    "assets/images/Marriage-Wedding/attraction-crushes.jpg",
    "assets/images/Marriage-Wedding/chemistry-connection.jpg",
    "assets/images/Marriage-Wedding/dating-courtship.jpg",
    "assets/images/Marriage-Wedding/flirting-seducing.jpg",
    "assets/images/Marriage-Wedding/friends-acquaintances.jpg",
    "assets/images/Marriage-Wedding/gays-lesbians.jpg",
    "assets/images/Marriage-Wedding/harmony-compatibility.jpg",
    "assets/images/Marriage-Wedding/heartbreaks-breakups.jpg",
    "assets/images/Marriage-Wedding/hookups-affairs.jpg",
    "assets/images/Marriage-Wedding/infidelity-cheating.jpg",
    "assets/images/Marriage-Wedding/ispace1-stripe.jpg",
    "assets/images/Marriage-Wedding/ispace1-world.jpg",
    "assets/images/Marriage-Wedding/love-romance.jpg",
    "assets/images/Marriage-Wedding/marriage-matrimony.jpg",
    "assets/images/Marriage-Wedding/relationship-commitment.jpg",
    "assets/images/Marriage-Wedding/sex-intimacy.jpg",
    "assets/images/Marriage-Wedding/singles-unattached.jpg",
    "assets/images/Marriage-Wedding/spouses-couples.jpg"
]
export const OpenRelationship = [
    "assets/images/Open-Relationship/attraction-crushes.jpg",
    "assets/images/Open-Relationship/chemistry-connection.jpg",
    "assets/images/Open-Relationship/dating-courtship.jpg",
    "assets/images/Open-Relationship/flirting-seducing.jpg",
    "assets/images/Open-Relationship/friends-acquaintances.jpg",
    "assets/images/Open-Relationship/gays-lesbians.jpg",
    "assets/images/Open-Relationship/harmony-compatibility.jpg",
    "assets/images/Open-Relationship/heartbreaks-breakups.jpg",
    "assets/images/Open-Relationship/hookups-affairs.jpg",
    "assets/images/Open-Relationship/infidelity-cheating.jpg",
    "assets/images/Open-Relationship/ispace1-stripe.jpg",
    "assets/images/Open-Relationship/ispace1-world.jpg",
    "assets/images/Open-Relationship/love-romance.jpg",
    "assets/images/Open-Relationship/marriage-matrimony.jpg",
    "assets/images/Open-Relationship/relationship-commitment.jpg",
    "assets/images/Open-Relationship/sex-intimacy.jpg",
    "assets/images/Open-Relationship/singles-unattached.jpg",
    "assets/images/Open-Relationship/spouses-couples.jpg"
]
export const QuotesSayings = [
    "assets/images/quotes-sayings/attraction-crushes.jpg",
    "assets/images/quotes-sayings/chemistry-connection.jpg",
    "assets/images/quotes-sayings/dating-courtship.jpg",
    "assets/images/quotes-sayings/flirting-seducing.jpg",
    "assets/images/quotes-sayings/friends-acquaintances.jpg",
    "assets/images/quotes-sayings/gays-lesbians.jpg",
    "assets/images/quotes-sayings/harmony-compatibility.jpg",
    "assets/images/quotes-sayings/heartbreaks-breakups.jpg",
    "assets/images/quotes-sayings/hookups-affairs.jpg",
    "assets/images/quotes-sayings/infidelity-cheating.jpg",
    "assets/images/quotes-sayings/ispace1-stripe.jpg",
    "assets/images/quotes-sayings/ispace1-world.jpg",
    "assets/images/quotes-sayings/love-romance.jpg",
    "assets/images/quotes-sayings/marriage-matrimony.jpg",
    "assets/images/quotes-sayings/relationship-commitment.jpg",
    "assets/images/quotes-sayings/sex-intimacy.jpg",
    "assets/images/quotes-sayings/singles-unattached.jpg",
    "assets/images/quotes-sayings/spouses-couples.jpg"
]
export const RelationshipCommitment = [
    "assets/images/Relationship-Commitment/attraction-crushes.jpg",
    "assets/images/Relationship-Commitment/chemistry-connection.jpg",
    "assets/images/Relationship-Commitment/dating-courtship.jpg",
    "assets/images/Relationship-Commitment/flirting-seducing.jpg",
    "assets/images/Relationship-Commitment/friends-acquaintances.jpg",
    "assets/images/Relationship-Commitment/gays-lesbians.jpg",
    "assets/images/Relationship-Commitment/harmony-compatibility.jpg",
    "assets/images/Relationship-Commitment/heartbreaks-breakups.jpg",
    "assets/images/Relationship-Commitment/hookups-affairs.jpg",
    "assets/images/Relationship-Commitment/infidelity-cheating.jpg",
    "assets/images/Relationship-Commitment/ispace1-stripe.jpg",
    "assets/images/Relationship-Commitment/ispace1-world.jpg",
    "assets/images/Relationship-Commitment/love-romance.jpg",
    "assets/images/Relationship-Commitment/marriage-matrimony.jpg",
    "assets/images/Relationship-Commitment/relationship-commitment.jpg",
    "assets/images/Relationship-Commitment/sex-intimacy.jpg",
    "assets/images/Relationship-Commitment/singles-unattached.jpg",
    "assets/images/Relationship-Commitment/spouses-couples.jpg"
]
export const SexIntimacy = [
    "assets/images/Sex-Intimacy/attraction-crushes.jpg",
    "assets/images/Sex-Intimacy/chemistry-connection.jpg",
    "assets/images/Sex-Intimacy/dating-courtship.jpg",
    "assets/images/Sex-Intimacy/flirting-seducing.jpg",
    "assets/images/Sex-Intimacy/friends-acquaintances.jpg",
    "assets/images/Sex-Intimacy/gays-lesbians.jpg",
    "assets/images/Sex-Intimacy/harmony-compatibility.jpg",
    "assets/images/Sex-Intimacy/heartbreaks-breakups.jpg",
    "assets/images/Sex-Intimacy/hookups-affairs.jpg",
    "assets/images/Sex-Intimacy/infidelity-cheating.jpg",
    "assets/images/Sex-Intimacy/ispace1-stripe.jpg",
    "assets/images/Sex-Intimacy/ispace1-world.jpg",
    "assets/images/Sex-Intimacy/love-romance.jpg",
    "assets/images/Sex-Intimacy/marriage-matrimony.jpg",
    "assets/images/Sex-Intimacy/relationship-commitment.jpg",
    "assets/images/Sex-Intimacy/sex-intimacy.jpg",
    "assets/images/Sex-Intimacy/singles-unattached.jpg",
    "assets/images/Sex-Intimacy/spouses-couples.jpg"
]
export const ShortRelationship = [
    "assets/images/Short-Relationship/attraction-crushes.jpg",
    "assets/images/Short-Relationship/chemistry-connection.jpg",
    "assets/images/Short-Relationship/dating-courtship.jpg",
    "assets/images/Short-Relationship/flirting-seducing.jpg",
    "assets/images/Short-Relationship/friends-acquaintances.jpg",
    "assets/images/Short-Relationship/gays-lesbians.jpg",
    "assets/images/Short-Relationship/harmony-compatibility.jpg",
    "assets/images/Short-Relationship/heartbreaks-breakups.jpg",
    "assets/images/Short-Relationship/hookups-affairs.jpg",
    "assets/images/Short-Relationship/infidelity-cheating.jpg",
    "assets/images/Short-Relationship/ispace1-stripe.jpg",
    "assets/images/Short-Relationship/ispace1-world.jpg",
    "assets/images/Short-Relationship/love-romance.jpg",
    "assets/images/Short-Relationship/marriage-matrimony.jpg",
    "assets/images/Short-Relationship/relationship-commitment.jpg",
    "assets/images/Short-Relationship/sex-intimacy.jpg",
    "assets/images/Short-Relationship/singles-unattached.jpg",
    "assets/images/Short-Relationship/spouses-couples.jpg"
]
export const SinglesUnattached = [
    "assets/images/Singles-Unattached/attraction-crushes.jpg",
    "assets/images/Singles-Unattached/chemistry-connection.jpg",
    "assets/images/Singles-Unattached/dating-courtship.jpg",
    "assets/images/Singles-Unattached/flirting-seducing.jpg",
    "assets/images/Singles-Unattached/friends-acquaintances.jpg",
    "assets/images/Singles-Unattached/gays-lesbians.jpg",
    "assets/images/Singles-Unattached/harmony-compatibility.jpg",
    "assets/images/Singles-Unattached/heartbreaks-breakups.jpg",
    "assets/images/Singles-Unattached/hookups-affairs.jpg",
    "assets/images/Singles-Unattached/infidelity-cheating.jpg",
    "assets/images/Singles-Unattached/ispace1-stripe.jpg",
    "assets/images/Singles-Unattached/ispace1-world.jpg",
    "assets/images/Singles-Unattached/love-romance.jpg",
    "assets/images/Singles-Unattached/marriage-matrimony.jpg",
    "assets/images/Singles-Unattached/relationship-commitment.jpg",
    "assets/images/Singles-Unattached/sex-intimacy.jpg",
    "assets/images/Singles-Unattached/singles-unattached.jpg",
    "assets/images/Singles-Unattached/spouses-couples.jpg"
]
export const SpousesCouples = [
    "assets/images/Spouses-Couples/attraction-crushes.jpg",
    "assets/images/Spouses-Couples/chemistry-connection.jpg",
    "assets/images/Spouses-Couples/dating-courtship.jpg",
    "assets/images/Spouses-Couples/flirting-seducing.jpg",
    "assets/images/Spouses-Couples/friends-acquaintances.jpg",
    "assets/images/Spouses-Couples/gays-lesbians.jpg",
    "assets/images/Spouses-Couples/harmony-compatibility.jpg",
    "assets/images/Spouses-Couples/heartbreaks-breakups.jpg",
    "assets/images/Spouses-Couples/hookups-affairs.jpg",
    "assets/images/Spouses-Couples/infidelity-cheating.jpg",
    "assets/images/Spouses-Couples/ispace1-stripe.jpg",
    "assets/images/Spouses-Couples/ispace1-world.jpg",
    "assets/images/Spouses-Couples/love-romance.jpg",
    "assets/images/Spouses-Couples/marriage-matrimony.jpg",
    "assets/images/Spouses-Couples/relationship-commitment.jpg",
    "assets/images/Spouses-Couples/sex-intimacy.jpg",
    "assets/images/Spouses-Couples/singles-unattached.jpg",
    "assets/images/Spouses-Couples/spouses-couples.jpg"
]
export const VirtualRelationship = [
    "assets/images/Virtual-Relationship/attraction-crushes.jpg",
    "assets/images/Virtual-Relationship/chemistry-connection.jpg",
    "assets/images/Virtual-Relationship/dating-courtship.jpg",
    "assets/images/Virtual-Relationship/flirting-seducing.jpg",
    "assets/images/Virtual-Relationship/friends-acquaintances.jpg",
    "assets/images/Virtual-Relationship/gays-lesbians.jpg",
    "assets/images/Virtual-Relationship/harmony-compatibility.jpg",
    "assets/images/Virtual-Relationship/heartbreaks-breakups.jpg",
    "assets/images/Virtual-Relationship/hookups-affairs.jpg",
    "assets/images/Virtual-Relationship/infidelity-cheating.jpg",
    "assets/images/Virtual-Relationship/ispace1-stripe.jpg",
    "assets/images/Virtual-Relationship/ispace1-world.jpg",
    "assets/images/Virtual-Relationship/love-romance.jpg",
    "assets/images/Virtual-Relationship/marriage-matrimony.jpg",
    "assets/images/Virtual-Relationship/relationship-commitment.jpg",
    "assets/images/Virtual-Relationship/sex-intimacy.jpg",
    "assets/images/Virtual-Relationship/singles-unattached.jpg",
    "assets/images/Virtual-Relationship/spouses-couples.jpg"
]
